In [47]:
pip install biopython

Note: you may need to restart the kernel to use updated packages.


In [48]:
from Bio.PDB import *
pdbl = PDBList()
pdbl.retrieve_pdb_file('4XP1')

Structure exists: '/Users/ankitapawar/Downloads/xp/4xp1.cif' 


'/Users/ankitapawar/Downloads/xp/4xp1.cif'

In [50]:
import os
os.listdir()

['WhatsApp Image 2021-05-31 at 12.04.31.jpeg',
 'Lect1-R.pptx',
 'googlechrome.dmg',
 'Covid_sequence.fasta',
 'Practical Assignment-6.pdf',
 'Lab1_Qn1(Roll no 2) (2).ipynb',
 'AndroidFileTransfer.dmg',
 'Python originals',
 'TIME&WORK -2.pptx',
 'Lect2 (2).pptx',
 'Bioinfo ppt edited.pptx',
 'Apple Inc vs Samsung Patent Infringement.docx',
 'operations.html',
 'document.pdf',
 'Biochem_ppt(Roll no 2 & 9).ppt',
 'Cytoskeleton_MSc_revised.pptx',
 'Intermediate Filaments.pptx',
 'Ankita.xlsx',
 'Q9NQX3_archive-PDB',
 'Lab1_Qn4(Roll no 2).ipynb',
 'Stem cell basics (1) (1).pptx',
 'Declaration - Return to Campus.pdf',
 'Stem cell basics final.pdf',
 '1-s2.0-S0306987721002255-main.pdf',
 '2021_11_29 8_19 PM Office Lens.pdf',
 'WhatsApp Image 2021-12-01 at 20.24.05 (5).jpeg',
 'Stem cell basics (1).pptx',
 '(Elsevier insights) Akira Satoh  - Introduction to practice of molecular simulation _ molecular dynamics, Monte Carlo, Brownian dynamics, Lattice Boltzmann, dissipative particle dynamics

In [51]:
os.listdir('xp')

['4xp1.cif']

In [52]:
# Parsing structure file
parser = MMCIFParser()

In [53]:
structure = parser.get_structure('4XP1', 'xp/4xp1.cif')

/Users/ankitapawar/opt/anaconda3/lib/python3.9/site-packages/Bio/PDB/StructureBuilder.py:89: PDBConstructionWarning: WARNING: Chain A is discontinuous at line 7523.
  warnings.warn(
/Users/ankitapawar/opt/anaconda3/lib/python3.9/site-packages/Bio/PDB/StructureBuilder.py:89: PDBConstructionWarning: WARNING: Chain L is discontinuous at line 7658.
  warnings.warn(
/Users/ankitapawar/opt/anaconda3/lib/python3.9/site-packages/Bio/PDB/StructureBuilder.py:89: PDBConstructionWarning: WARNING: Chain A is discontinuous at line 7659.
  warnings.warn(
/Users/ankitapawar/opt/anaconda3/lib/python3.9/site-packages/Bio/PDB/StructureBuilder.py:89: PDBConstructionWarning: WARNING: Chain L is discontinuous at line 7674.
  warnings.warn(
/Users/ankitapawar/opt/anaconda3/lib/python3.9/site-packages/Bio/PDB/StructureBuilder.py:89: PDBConstructionWarning: WARNING: Chain H is discontinuous at line 7677.
  warnings.warn(


In [54]:
def cleandir(obj):
    print(", ".join([a for a in dir(obj) if not a.startswith("_")]))
cleandir(structure)

add, atom_to_internal_coordinates, center_of_mass, child_dict, child_list, copy, detach_child, detach_parent, full_id, get_atoms, get_chains, get_full_id, get_id, get_iterator, get_level, get_list, get_models, get_parent, get_residues, has_id, header, id, insert, internal_to_atom_coordinates, level, parent, set_parent, transform, xtra


In [ ]:
########  Visualizing structures in jupyter Notebooks   #########

In [55]:
pip install nglview

Note: you may need to restart the kernel to use updated packages.


In [56]:
import nglview as nv

In [61]:
view = nv.show_biopython(structure)
view.clear_representations()

#view as ball and stick (atom and bond)
view.add_ball_and_stick()

In [62]:
view

NGLWidget()

In [59]:
view.clear_representations()

#add ribbons
view.add_cartoon('protein')

#add ball and stick for non-rotien
view.add_ball_and_stick('not protein')

In [60]:
view

NGLWidget(n_components=1)

In [63]:
for model in structure:
    print(f"model {model}")

model <Model id=0>


In [64]:
model = structure[0] #since we only have one model
for chain in model:
    print(f"chain {chain}, Chain ID: {chain.id}")

chain <Chain id=A>, Chain ID: A
chain <Chain id=L>, Chain ID: L
chain <Chain id=H>, Chain ID: H
chain <Chain id=B>, Chain ID: B
chain <Chain id=C>, Chain ID: C


In [65]:
chain_A = model['A']

In [66]:
for res in chain_A:
    print(f"Residue name: {res.resname}, number: {res.id[1]}")

Residue name: ASP, number: 25
Residue name: GLU, number: 26
Residue name: ARG, number: 27
Residue name: GLU, number: 28
Residue name: THR, number: 29
Residue name: TRP, number: 30
Residue name: SER, number: 31
Residue name: GLY, number: 32
Residue name: LYS, number: 33
Residue name: VAL, number: 34
Residue name: ASP, number: 35
Residue name: PHE, number: 36
Residue name: LEU, number: 37
Residue name: LEU, number: 38
Residue name: SER, number: 39
Residue name: VAL, number: 40
Residue name: ILE, number: 41
Residue name: GLY, number: 42
Residue name: PHE, number: 43
Residue name: ALA, number: 44
Residue name: VAL, number: 45
Residue name: ASP, number: 46
Residue name: LEU, number: 47
Residue name: ALA, number: 48
Residue name: ASN, number: 49
Residue name: VAL, number: 50
Residue name: TRP, number: 51
Residue name: ARG, number: 52
Residue name: PHE, number: 53
Residue name: PRO, number: 54
Residue name: TYR, number: 55
Residue name: LEU, number: 56
Residue name: CYS, number: 57
Residue na

In [67]:
res = chain_A[56]

In [68]:
print(res)

<Residue LEU het=  resseq=56 icode= >


In [69]:
for atom in res:
    print(f"{atom.name}")

N
CA
C
O
CB
CG
CD1
CD2


In [70]:
for model in structure:
    for chain in model:
        for residue in chain:
            for atom in residue:
                print(atom)

<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom OD1>
<Atom OD2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD>
<Atom OE1>
<Atom OE2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD>
<Atom NE>
<Atom CZ>
<Atom NH1>
<Atom NH2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD>
<Atom OE1>
<Atom OE2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom OG1>
<Atom CG2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD1>
<Atom CD2>
<Atom NE1>
<Atom CE2>
<Atom CE3>
<Atom CZ2>
<Atom CZ3>
<Atom CH2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom OG>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD>
<Atom CE>
<Atom NZ>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG1>
<Atom CG2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom OD1>
<Atom OD2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD1>
<Atom CD2>
<Atom CE1>
<

In [22]:
###### Mini project: find the dopamine binding pockets ######

In [92]:
struc_dict = MMCIF2Dict.MMCIF2Dict('xp/4xp1.cif')

In [93]:
print(struc_dict.keys())

dict_keys(['data_', '_entry.id', '_audit_conform.dict_name', '_audit_conform.dict_version', '_audit_conform.dict_location', '_database_2.database_id', '_database_2.database_code', '_pdbx_database_related.db_name', '_pdbx_database_related.details', '_pdbx_database_related.db_id', '_pdbx_database_related.content_type', '_pdbx_database_status.status_code', '_pdbx_database_status.status_code_sf', '_pdbx_database_status.status_code_mr', '_pdbx_database_status.entry_id', '_pdbx_database_status.recvd_initial_deposition_date', '_pdbx_database_status.SG_entry', '_pdbx_database_status.deposit_site', '_pdbx_database_status.process_site', '_pdbx_database_status.status_code_cs', '_pdbx_database_status.methods_development_category', '_pdbx_database_status.pdb_format_compatible', '_pdbx_database_status.status_code_nmr_data', '_audit_author.name', '_audit_author.pdbx_ordinal', '_citation.abstract', '_citation.abstract_id_CAS', '_citation.book_id_ISBN', '_citation.book_publisher', '_citation.book_publi

In [108]:
struc_dict['_pdbx_entity_nonpoly.comp_id']

['NA', 'CL', 'NAG', 'P4G', 'LDP', 'EDO', 'Y01', 'CLR', 'HOH']

In [111]:
struc_dict['_pdbx_struct_oper_list.name']

['1_555']

In [112]:
struc_dict['_struct_conn.id']

['disulf1',
 'disulf2',
 'disulf3',
 'disulf4',
 'disulf5',
 'covale1',
 'covale2',
 'covale3',
 'metalc1',
 'metalc2',
 'metalc3',
 'metalc4',
 'metalc5',
 'metalc6',
 'metalc7',
 'metalc8',
 'metalc9',
 'metalc10',
 'metalc11',
 'metalc12',
 'metalc13']

In [114]:
struc_dict['_struct_sheet.type']

['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?']

In [78]:
struc_dict['_citation.title']

['Neurotransmitter and psychostimulant recognition by the dopamine transporter.']

In [104]:
#site_ID = struc_dict['_struct_site_gen.site_id']
#site_chain = struc_dict['_struct_site_gen.auth_asym_id']
#site_resnum = struc_dict['_struct_site_gen.auth_seq_id']
#site_resname = struc_dict['_struct_site_gen.label_comp_id']

#cif_binding_residues = []
#for bind_id, ch, num, name in zip(site_ID, site_chain, site_resnum, site_resname):
#    if bind_id == "AC7":
#        print(bind_id, ch, num, name)
#        try:
#            cif_binding_residues.append(structure[0][ch][int(num)])
#        except:
#            continue
#    else:
#        continue

In [83]:
#finding LDP residue
LDP = None
for res in structure[0].get_residues():
    if res.resname == "LDP":
        LDP = res
        break
print(LDP)

<Residue LDP het=H_LDP resseq=708 icode= >


In [115]:
res_1_CA = structure[0]['A'][56]['CA']
print(res_1_CA.coord)

[  3.765 -10.389 -31.972]


In [116]:
res_2_CA = structure[0]['A'][327]['CA']
print(res_2_CA.coord)

[-12.762   9.25  -31.894]


In [117]:
diff = res_1_CA.coord - res_2_CA.coord
print(diff)

[ 16.527      -19.639       -0.07800102]


In [118]:
import numpy as np
dist = np.sqrt(diff * diff)
print(dist)

[16.527      19.639       0.07800102]


In [119]:
cutoff = 10

binding_residues = []

for res in structure[0].get_residues():
    #skip the LDP residue
    if res == LDP:
        continue
    #non-amino acid residues are tagged with an 'H' in their id tuple
    #we want to skip these
    elif res.id[0].startswith("H"):
        continue
    else:
        alpha_carbon = res['CA']
        distances = []
        for atom in LDP:
            #subtract the two position vectors
            diff_vector = alpha_carbon.coord - atom.coord
            #to get a positive value we square the difference vector
            #we then take the square root to go back to the original scale
            distances.append(np.sqrt(np.sum(diff_vector * diff_vector)))
        #we get the nearest atom using min(distances) and see if it falls inside
        #the cutoff
        if min(distances) < cutoff:
            binding_residues.append(res)

KeyError: 'CA'

In [106]:
print(binding_residues)

[<Residue GLY het=  resseq=42 icode= >, <Residue PHE het=  resseq=43 icode= >, <Residue ALA het=  resseq=44 icode= >, <Residue VAL het=  resseq=45 icode= >, <Residue ASP het=  resseq=46 icode= >, <Residue LEU het=  resseq=47 icode= >, <Residue ALA het=  resseq=48 icode= >, <Residue ASN het=  resseq=49 icode= >, <Residue VAL het=  resseq=113 icode= >, <Residue VAL het=  resseq=114 icode= >, <Residue LEU het=  resseq=115 icode= >, <Residue ILE het=  resseq=116 icode= >, <Residue ALA het=  resseq=117 icode= >, <Residue PHE het=  resseq=118 icode= >, <Residue TYR het=  resseq=119 icode= >, <Residue VAL het=  resseq=120 icode= >, <Residue ASP het=  resseq=121 icode= >, <Residue PHE het=  resseq=122 icode= >, <Residue TYR het=  resseq=123 icode= >, <Residue TYR het=  resseq=124 icode= >, <Residue ASN het=  resseq=125 icode= >, <Residue VAL het=  resseq=126 icode= >, <Residue ILE het=  resseq=127 icode= >, <Residue ILE het=  resseq=128 icode= >, <Residue CYS het=  resseq=250 icode= >, <Residu

In [120]:
import nglview as nv

In [124]:
#import seaborn as sns
view = nv.demo()
view = nv.show_biopython(structure)

# use hex values for now.
residues = structure[0].get_residues()

#this is a bit of a hack to set the binding residues to red in the visualization
colors = ['0x0000FF' if r not in binding_residues else '0xFF0000' for r in residues]
#view._set_color_by_residue(colors, component_index=0, repr_index=0)
view

NGLWidget()

In [125]:
view = nv.show_biopython(structure)

# use hex values for now.
residues = structure[0].get_residues()
#this is a bit of a hack to set the binding residues to red in the visualization
colors = ['0x0000FF' if r not in cif_binding_residues else '0xFF0000' for r in residues]
#view._set_color_by_residue(colors, component_index=0, repr_index=0)
view

NGLWidget()